# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x' ]
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '12'      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |        
          sh ./build-app.sh
          
      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r TourManagerUI-Angular.zip ./AngularApp/dist/TourManagerUI/
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./TourManagerUI-Angular.zip
          asset_name: TourManagerUI-Angular.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: | 
            cp ./TourManager.UI.Angular/TourManagerWeb/wwwroot/index.html ./TourManager.UI.Angular/TourManagerWeb/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Commit wwwroot to GitHub Pages      
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./TourManager.UI.Angular/TourManagerWeb/wwwroot/
.
          
          
        
          
